import type { Metadata } from "next";
import { Geist, Geist_Mono, Raleway } from "next/font/google";
import "./globals.css";
import GeistWrapper from "@/components/GeistWrapper";
import Footer from "@/components/footer/Footer";
import Navbar from "@/components/navbar/Navbar";
import SessionClientProvider from "@/components/SessionClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const raleway = Raleway({
  variable: "--font-raleway",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${raleway.variable} font-[var(--font-raleway)] antialiased`}
      >
        <GeistWrapper>
          <SessionClientProvider>
            <Navbar />
            <div className="flex-1">{children}</div>
            <Footer />
          </SessionClientProvider>
        </GeistWrapper>
      </body>
    </html>
  );
}
